import Head from 'next/head'
import Navbar from '@/components/Navbar'
import HeroSection from '@/components/HeroSection'
import SaleDiscount from '@/components/SaleDiscount'
import DisplayImages from '@/components/DisplayImages'
import SliderImg from '@/components/SliderImg'
import SalesComponent from '@/components/SalesComponent'
import SubscribeForm from '@/components/SubscribeForm'
import TrendColl from '@/components/TrendColl'
import ContentSlider from '@/components/ContentSlider'
import Footer from '@/components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Fashion Store</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/store.ico' />
      </Head>
      <main>
        <Navbar />
      </main>
      <section>
        <HeroSection />
      </section>
      <section>
        <SaleDiscount />
      </section>
      <section>
        <DisplayImages />
      </section>
      <section className='px-[1.125rem]'>
        <div className='flex flex-col gap-[0.6875rem] items-center mb-[3.3125rem] justify-center'>
          <h2 className='font-ubuntu font-bold text-[2.5rem] leading-[4.3125rem] text-primaryFashion md:text-[3.125rem] lg:text-[3.75rem] '>
            Best Sellers
          </h2>
          <p className='font-ubuntu font-normal text-base leading-[1.4375rem] text-center text-primaryFashion opacity-50 md:text-[1.25rem]'>
            Check out most promising product bought by our buyers
          </p>
        </div>
        <SliderImg />
      </section>
      <section className='mb-[6.6806rem] lg:mb-[12.6806rem] '>
        <SalesComponent />
      </section>
      <section className='mb-[133px]'>
        <SubscribeForm />
      </section>
      <section className='mb-[9.625rem]'>
        <TrendColl />
      </section>
      <section className='mb-[75px]'>
        <ContentSlider />
      </section>
      <footer className='px-8 py-[94px] md:px-12 lg:pl-[100px] lg:pr-[100px] bg-[#323232]'>
        <Footer />
      </footer>
    </>
  )
}
